version: "3.8"

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - "./backend:/home/app/"
      - /home/app/node_modules
    ports:
      - "8080:8080"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: "on-failure:10"

  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - "./client:/home/app/"
      - /home/app/node_modules
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - "3000:3000"
